[package]
name = "rust-console-game"
version = "0.1.0"
authors = ["Graham King <graham@gkgk.org>"]
edition = "2018"

[dependencies]
crossterm = "0.19.0"
lazy_static = "1.4.0"
log = "0.4.14"
rand = "0.8.4"
simplelog = "0.10.0"
