[package]
name = "console"
version = "0.1.0"
authors = ["Graham King <graham@gkgk.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.19.0"
log = "0.4.14"
simplelog = "0.10.0"
